apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rest-fights-hpa
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1 
    kind: DeploymentConfig
    name: rest-fights
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 40
          type: Utilization
