apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
 name: rest-fights-vpa
spec:
 targetRef:
   apiVersion: "apps.openshift.io/v1"
   kind: DeploymentConfig
   name: rest-fights
 updatePolicy:
   updateMode: "Off"
